server:
  port: 8080

    
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/jdbc_demo
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always  
